[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions" 
base = "/"

[dev]
  framework = "vite"
  targetPort = 5173

[[redirects]]

from = "/*"
to = "/index.html"
status = 200

[functions]
node_bundler = "esbuild"

[build.environment]
NODE_VERSION = "20"